# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuDeJieGY' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BuDeJieGY
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'DACircularProgress', '~> 2.3.1'
  pod 'MJRefresh', '~> 3.1.15.7'
  pod 'SDWebImage', :path => '~/Downloads/iOSFrame/SDWebImage/SDWebImage-5.0.3’
  pod 'YZDisplayViewController', :path => '~/Downloads/iOSFrame/YZDisplayViewController/YZDisplayViewController-master’
  #pod 'JTNavigationController', :path => '~/Downloads/iOSFrame/JTNavigationController-master/JTNavigationController’
end

