# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuDeJieGY' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BuDeJieGY
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'SDWebImage', :path => '~/Downloads/iOSFrame/SDWebImage-5.0.3’
  pod 'YZDisplayViewController', :path => '~/Downloads/iOSFrame/YZDisplayViewController-master’
  #pod 'JTNavigationController', :path => '~/Downloads/iOSFrame/JTNavigationController-master/JTNavigationController’
end

